### ISSUE TITLE
دیزاین مجدد صفحه‌ی اصلی

### ISSUE THREAD

**Issue by Sinusealpha** [Sinusealpha/MedX#1]
تصمیم‌گیری درمورد این موضوعات:
- چه چیزهایی در صفحه‌ی اصلی قرار بگیرند؟
- بنر در کجای صفحه قرار بگیرد؟
- پست‌تایپ‌ها به چه صورت طراحی و در صفحه‌ی اصلی قرار بگیرند؟
- هدر و فوتر چه بخش‌ها و جزئیاتی داشته باشند؟

**Comment by Sinusealpha** [comment]
> تصمیم‌گیری درمورد این موضوعات:
> 
> * چه چیزهایی در صفحه‌ی اصلی قرار بگیرند؟
> * بنر در کجای صفحه قرار بگیرد؟
> * پست‌تایپ‌ها به چه صورت طراحی و در صفحه‌ی اصلی قرار بگیرند؟
> * هدر و فوتر چه بخش‌ها و جزئیاتی داشته باشند؟

خب درمورد دیزاین صفحه‌ی اصلی باید این نکات رو در نظر بگیریم.

هدف = مشاهده‌ی یک نمای کلی از تمام خدماتی که کاربر می‌تواند از وبسایت بگیرد. مسلما مهم‌ترین خدمات بالاتر و جلوتر قرار خواهند گرفت.
توضیحات جزئیات مهم:
- بنر: یک بنر خواهیم داشت که بالا-راست قرار می‌گیرد. عرض آن ۷۰٪ عرض تمام‌صفحه و طول آن هم ۵۰٪ طول تمام‌صفحه است. بنر قرار است مهم‌ترین اخبار را نشان بدهد. مهم‌ترین اخبار از پربازدیدترین پست‌هایی که کاربران در یک هفته‌ی اخیر نوشته‌اند انتخاب می‌شود. اصول نوشتن پست‌های خبری را هم در ایشوی مجزایی توضیح خواهم داد.
- پربازدیدترین وبلاگ‌ها: کاربران وبلاگ‌هایی را هم مجزا از اخبار می‌نویسند و ما پربازدیدترین‌هایشان را در صفحه‌ی اصلی نشان خواهیم داد. اما نکته این‌جاست که این‌بار نه به صورت بنر بلکه به صورت پست‌های کنار هم قرار گرفته‌ای که قابلیت «بیشتر» دارند. به این معنی که فرد می‌تواند با کلیک بر روی دکمه‌ی بیشتر پست‌های وبلاگی بیشتری را بر اساس بیشترین بازدید در یک ماه اخیر ببیند. این بخش در زیر پربازدیدترین دوره‌ها قرار بگیرد و ۷۰٪ عرض صفحه را داشته باشد.
- پربازدیدترین دوره‌ها: این بخش طراحی شود. اما عبارت «هنوز دوره‌ای برگزار نشده است» در درون باکس مربوط به آن قرار بگیرد. این بخش در زیر بخش اخبار قرار بگیرد و ۷۰٪ عرض صفحه را داشته باشد و طولش طوری نشود که پربازدیدتری وبلاگ‌ها دیده نشوند. هدف این است که بخشی از پربازدیدترین وبلاگ‌ها دیده شوند تا کاربر برای مشاهده‌ی ادامه‌ی صفحه اسکرول کند.
- پربازدیدترین واژه‌های واژه‌نامه (اسم بهترین به ذهن‌تون می‌رسه؟): این بخش هم در سمت چپ در کنار بنر اخبار قرار بگیرد.

این‌ها مهم‌ترین بخش‌ها هستند. بخش‌های دیگری هم در ادامه ممکن است اضافه شوند. اما درمورد همین بخش‌ها اگر جایی از پیام من مبهم بود و یا منظور رو نرسوند بگید تا دقیق توضیح بدم. @aref-asadi

**Comment by aref-asadi** [comment]
We decided to implement our website with code instead of using WordPress.
