### ISSUE TITLE
Create a Telegram Bot to Send GitHub Notifications to a Telegram Channel

### ISSUE THREAD

**Issue by hossein-kazzemi** [Sinusealpha/MedX#12]
سلام. از اونجایی که تقریبا هسته مرکزی ارتباط های تمام ایران، تلگرام هست و ما هم از این قائله مستثنا نیستیم. پس تصمیم گرفتیم برای اینکه این روند ارتباط رو تسهلیش کنیم فرایند های توی گیت هاب رو توسط یه ربات تلگرام به اونجا هم ببریم. چرا ؟ از اونجایی که ما توی تلگرام خیلی فعالیم چقدر عالی میشه که بتونیم حتی زودتر از تغییراتی که توی گیت هاب ما اتفاق افتاده مطلع بشیم. این ربات قراره کمکمون کنه تا این کار رو انجام بدیم و هر چیزی که توی گیت هاب اضافه یا کم بشه، توی تلگرام ازش مطلع میشیم.

**Comment by BDadmehr0** [comment]
فکر میکنم برای اینکه بتونید این کار رو انجام دهد نیاز به چک تغییرات و commit های گیت هاب توسط ربات تلگرامی را دارید و اپلود ان روی گروه کانال یا ارسال به pv

**Comment by hossein-kazzemi** [comment]
> فکر میکنم برای اینکه بتونید این کار رو انجام دهد نیاز به چک تغییرات و commit های گیت هاب توسط ربات تلگرامی را دارید و اپلود ان روی گروه کانال یا ارسال به pv
> 
> بنده حاضرم کمک کنم لطفا مراحل را دقیق بیان کنید

درست میگید. ما یه ربات تلگرامی باید بنویسیم که ادمین یه کانال عمومی هست و تغییرات گیتهاب رو اونجا پست می‌کنه. این کار رو می‌تونید انجام بدید؟ اگر بله ممنون میشم توی تلگرام بهم پیام بدید تا لینک کانال رو براتون بفرستم.
ID : @hossein_kazzemi

**Comment by hossein-kazzemi** [comment]
ددلاین ایشو : 30 تیر 1403

**Comment by aref-asadi** [comment]
Description:
We need to develop a Telegram bot that can automatically send GitHub notifications (such as new Issues, Pull Requests, and repository changes) to a Telegram channel. The bot should be continuously connected to GitHub and send notifications as soon as events occur.

Benefits:
- Automatic, fast & accessible notifications of changes in MedX GitHub repository.
- Improved project management and team awareness of updates.

Required Features:
- GitHub Integration:
The bot should connect to MedX GitHub repository and monitor all relevant events (Issues, Pull Requests, Commits, etc.).
- Notification Delivery to Telegram Channel:
The bot should send notifications about GitHub events as messages to a Telegram channel.

Implementation:
- We can use Webhooks to facilitate communication between GitHub and Telegram.
- We can implement the bot using Python.
- We should store configurations and settings in YAML or JSON files.

Tasks:
- [ ]  Set up the initial structure of the Telegram bot.
- [ ]  Implement the connection with GitHub using Webhooks.
- [ ]  Send notifications to the Telegram channel.
- [ ]  Document the setup and provide configuration guidelines.

**Comment by Lwantstostophim** [comment]
i need someone from telegram to help asap theres tons of people and channels posting selling trading csam of a friend who was 14 at the time and emailing telegram and reporting does nothing
