### ISSUE TITLE
دیزاین صفحات پنل کاربری

### ISSUE THREAD

**Issue by Sinusealpha** [Sinusealpha/MedX#2]
تصمیم‌گیری راجه‌به موارد زیر:
- صفحه‌ی اصلی کاربری چه مشخصه‌ها و فیچرهایی داشته باشد؟ چه صفحاتی از صفحه‌ی اصلی منشعب شوند؟
- هر کدام از صفحات منشعب‌شده از صفحه‌ی کاربری چه دیزاینی داشته باشند؟
- کدام فیچرها در اولویت هستند و ترتیب کارکردن آن‌ها باید به چه صورتی باشد؟

**Comment by hossein-kazzemi** [comment]
سلام

**Comment by Sinusealpha** [comment]
> تصمیم‌گیری راجه‌به موارد زیر:
> 
> * صفحه‌ی اصلی کاربری چه مشخصه‌ها و فیچرهایی داشته باشد؟ چه صفحاتی از صفحه‌ی اصلی منشعب شوند؟
> * هر کدام از صفحات منشعب‌شده از صفحه‌ی کاربری چه دیزاینی داشته باشند؟
> * کدام فیچرها در اولویت هستند و ترتیب کارکردن آن‌ها باید به چه صورتی باشد؟



اجزای پنل کاربران به این صورت خواهد بود:
- اطلاعات (عکس / نام / بیو / تعداد دنبال‌کننده / تعداد دنبال‌شونده / موضوعات مورد علاقه (بر اساس دسته‌بندی‌های اصلی که هنگام ثبت‌نام یک یا چندتایشان را انتخاب می‌کنند) / ...)
- خلاصه‌ای از فعالیت‌هایشان در مدیکس (تعداد روز عضویت / تعداد اخبار نوشته شده / تعداد وبلاگ نوشته شده / تعداد بازدید مطالب / تعداد لایک‌ها / تعداد کامنت‌هایی که برای دیگران گذاشته است / بیشترین ریپلای زده‌شده به «فلان» کاربر / بیشترین لایک‌شده توسط «فلان» کابر / تعداد کانتریبیوشن‌ها در دولوپمنت مدیکس / ...)
- جوایز برنده‌شده (پربازدیدترین نویسنده‌ی ماه / بیشترین کامنت‌گذار ماه / بیشترین کمک به دولوپمنت مدیکس / ... )
- دوره‌های من (دوره‌های فعال / دوره‌های گذشته) (یک دکمه‌ی برگزاری دوره هم وجود داشته باشد)

همین‌ها به نظرم اصلی می‌آیند. اولویت هم با اطلاعات و سپس خلاصه‌ای از فعالیت‌ها است. بقیه‌ی صفحات می‌توانند در ادامه اضافه شوند. اگر جایی از متن‌ام واضح نبود بگید که بیشتر توضیح بدم. @aref-asadi

**Comment by aref-asadi** [comment]
We decided to implement our website with code instead of using WordPress.
